/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotp1;

/**
 *
 * @author lflamellas
 */
public class screenLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public screenLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    background = new javax.swing.JPanel();
    logoShadow = new javax.swing.JLabel();
    passwordText = new javax.swing.JLabel();
    userText = new javax.swing.JLabel();
    inputUser = new javax.swing.JTextField();
    inputPassword = new javax.swing.JTextField();
    loginButton = new javax.swing.JButton();
    registerMessage = new javax.swing.JLabel();
    registerButton = new javax.swing.JLabel();
    pictureIcon = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setSize(new java.awt.Dimension(800, 500));

    background.setBackground(new java.awt.Color(47, 54, 89));
    background.setPreferredSize(new java.awt.Dimension(800, 500));
    background.setLayout(null);

    logoShadow.setFont(new java.awt.Font("Monospaced", 1, 64)); // NOI18N
    logoShadow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logoShadow.setText("XILFTEN");
    background.add(logoShadow);
    logoShadow.setBounds(80, 20, 280, 76);

    passwordText.setFont(new java.awt.Font("Cambay Devanagari", 1, 14)); // NOI18N
    passwordText.setForeground(new java.awt.Color(255, 255, 255));
    passwordText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    passwordText.setText("PASSWORD");
    background.add(passwordText);
    passwordText.setBounds(80, 300, 80, 30);

    userText.setFont(new java.awt.Font("Cambay Devanagari", 1, 14)); // NOI18N
    userText.setForeground(new java.awt.Color(255, 255, 255));
    userText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    userText.setText("USER");
    background.add(userText);
    userText.setBounds(80, 270, 80, 20);

    inputUser.setBackground(new java.awt.Color(153, 153, 255));
    inputUser.setFont(new java.awt.Font("Andale Mono", 0, 14)); // NOI18N
    inputUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    inputUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        inputUserActionPerformed(evt);
      }
    });
    background.add(inputUser);
    inputUser.setBounds(170, 270, 170, 20);

    inputPassword.setBackground(new java.awt.Color(153, 153, 255));
    inputPassword.setFont(new java.awt.Font("Andale Mono", 0, 14)); // NOI18N
    inputPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    inputPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        inputPasswordActionPerformed(evt);
      }
    });
    background.add(inputPassword);
    inputPassword.setBounds(170, 310, 170, 21);

    loginButton.setFont(new java.awt.Font("Cambay Devanagari", 1, 14)); // NOI18N
    loginButton.setText("LOGIN");
    loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        loginButtonMouseClicked(evt);
      }
    });
    background.add(loginButton);
    loginButton.setBounds(190, 340, 120, 27);

    registerMessage.setForeground(new java.awt.Color(255, 255, 255));
    registerMessage.setText("Not registered yet?");
    background.add(registerMessage);
    registerMessage.setBounds(190, 420, 120, 18);

    registerButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    registerButton.setForeground(new java.awt.Color(255, 255, 255));
    registerButton.setText("Register now!");
    registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        registerButtonMouseClicked(evt);
      }
    });
    background.add(registerButton);
    registerButton.setBounds(200, 440, 100, 17);

    pictureIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    pictureIcon.setText("ICON");
    pictureIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
    background.add(pictureIcon);
    pictureIcon.setBounds(180, 110, 128, 128);

    getContentPane().add(background, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void inputUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUserActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(screenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(screenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(screenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(screenLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new screenLogin().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel background;
  private javax.swing.JTextField inputPassword;
  private javax.swing.JTextField inputUser;
  private javax.swing.JButton loginButton;
  private javax.swing.JLabel logoShadow;
  private javax.swing.JLabel passwordText;
  private javax.swing.JLabel pictureIcon;
  private javax.swing.JLabel registerButton;
  private javax.swing.JLabel registerMessage;
  private javax.swing.JLabel userText;
  // End of variables declaration//GEN-END:variables
}
